#cloud-config
package_update: true
package_upgrade: true
runcmd:
  - "git clone https://github.com/angristan/openvpn-install.git && cd openvpn-install && ufw default deny incoming && ufw default allow outgoing && ufw allow ssh && ufw allow openvpn && ufw enable && AUTO_INSTALL=y DNS=9 CLIENT=default ./openvpn-install.sh
  - reboot